trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Azure subscription 1(ae3247b5-b388-4787-a41d-c153cbab0911)'
    backendAzureRmResourceGroupName: 'CloudPA'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra'   
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Azure subscription 1(ae3247b5-b388-4787-a41d-c153cbab0911)'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra'


