apiVersion: v1
kind: Service
metadata:
    name: "cloudpa-5a75"
    labels:
        app: "cloudpa-5a75"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "cloudpa-5a75"