on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: cloudpa.azurecr.io
        username: ${{ secrets.acr_cloudpa_username }}
        password: ${{ secrets.acr_cloudpa_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t cloudpa.azurecr.io/cloudpa:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push cloudpa.azurecr.io/cloudpa:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_cloudpa_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep cloudpaae8f | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace cloudpaae8f`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: cloudpaae8f
        container-registry-url: cloudpa.azurecr.io
        container-registry-username: ${{ secrets.acr_cloudpa_username }}
        container-registry-password: ${{ secrets.acr_cloudpa_password }}
        secret-name: cloudpadockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: cloudpaae8f
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress-1.yml
        images: |
          cloudpa.azurecr.io/cloudpa:${{ github.sha }}
        imagepullsecrets: |
          cloudpadockerauth
